#pytest.ini = global configuration file that defines Pytest’s rules and behavior for the entire framework

[pytest]
markers=
    smoke:these are smoke test
    regression:these are regression test
    sanity:these are sanity test
    negative: negative test cases
    validation: form validation tests